[project]
name = "data-agent"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "suranimayur", email = "surani.mayur@gmail.com" }
]
requires-python = ">=3.14"
dependencies = [
    "python-dotenv>=1.0.0",
    "langchain>=1.3.16",
    "langchain-ollama>=1.1.0",
    "langchain-openai>=1.6.0",
    "langgraph>=1.2.11",
    "pydantic>=2.13.4",
    "psycopg2>=2.9.12",
    "psycopg2-binary>=2.9.12",
    "ipython>=9.16.1",
    "openpyxl>=3.1.5",
    "jedi>=0.20.0",
    "pylance>=10.0.0",
    "pandas>=3.0.5",
]

[project.scripts]
data-agent = "data_agent:main"

[build-system]
requires = ["uv_build>=0.12.5,<0.13.0"]
build-backend = "uv_build"
