"""
Pydantic Schemas
================
Defines all state schemas used by LangGraph agents in the Intelligent Multi-Agent Data Engineering Platform.

These schemas serve two critical purposes:
1. **LangGraph State**: Define what data flows through each agent graph
2. **Structured Output**: Constrain LLM responses to specific formats

Schema Hierarchy:
    - DataAgentSchema: Top-level orchestrator state (routing)
    - AgentSchema: SQL Analyst state (question → SQL → result)
    - ETLAgentSchema: ETL Analyst state (tool-calling messages)
    - RouterSchema: LLM classification output (sql vs etl)
    - JudgeSchema: SQL safety validation output (Yes/No)
"""

from pydantic import BaseModel, Field
from typing import List, Literal, Annotated
from operator import add
from langchain_core.messages import BaseMessage
from langgraph.graph.message import add_messages


# ---------------------------------------------------------------------------
# SQL Analyst Schemas
# ---------------------------------------------------------------------------

class AgentSchema(BaseModel):
    """
    State schema for the SQL Analyst agent.

    Tracks the full lifecycle of a SQL query: from user question
    through curation, generation, safety validation, execution,
    and final answer formatting.
    """
    messages: list = Field(
        default_factory=list,
        description="Conversation message history",
    )
    user_question: str = Field(
        ...,
        description="The original natural language question from the user",
    )
    curated_question: str = Field(
        default="",
        description="Refined question optimized for SQL generation",
    )
    prompt_query_context: str = Field(
        default="",
        description="Full prompt with DB schema context for SQL generation",
    )
    generated_sql_query: str = Field(
        default="",
        description="SQL query generated by the LLM",
    )
    is_safe_sql: Literal["Yes", "No"] = Field(
        default="No",
        description="Whether the SQL query passed safety validation",
    )
    comments: str = Field(
        default="",
        description="Safety judge's explanation of the validation decision",
    )
    sql_query_execution_result: str = Field(
        default="",
        description="Raw result from executing the SQL query",
    )
    final_answer: str = Field(
        default="",
        description="Human-readable final answer for the user",
    )


class JudgeSchema(BaseModel):
    """
    Structured output schema for the SQL safety judge.

    The LLM uses this schema to classify SQL queries as safe or unsafe,
    preventing dangerous operations (DROP, DELETE, INSERT, etc.).
    """
    answer: Literal["Yes", "No"] = Field(
        ...,
        description="'Yes' if the query is safe (SELECT-only), 'No' otherwise",
    )
    comment: str = Field(
        ...,
        description="Explanation of the safety assessment decision",
    )


# ---------------------------------------------------------------------------
# ETL Analyst Schemas
# ---------------------------------------------------------------------------

class ETLAgentSchema(BaseModel):
    """
    State schema for the ETL Analyst agent.

    Uses LangGraph's add_messages reducer for intelligent message
    handling — appends new messages while maintaining conversation order.
    """
    messages: Annotated[List[BaseMessage], add_messages] = Field(
        ...,
        description="Message history for the ETL tool-calling agent",
    )


# ---------------------------------------------------------------------------
# Data Agent (Orchestrator) Schemas
# ---------------------------------------------------------------------------

class RouterSchema(BaseModel):
    """
    Structured output schema for the intent classifier.

    The LLM classifies each user question as either a SQL query
    request or an ETL operation request.
    """
    answer: Literal["sql", "etl"] = Field(
        ...,
        description="'sql' for database queries, 'etl' for data extraction/transformation",
    )
    comments: str = Field(
        ...,
        description="Explanation of why this classification was chosen",
    )


class DataAgentSchema(BaseModel):
    """
    State schema for the top-level Data Agent orchestrator.

    Routes user questions to the appropriate sub-agent (SQL or ETL)
    based on the router's classification.
    """
    messages: Annotated[list, add] = Field(
        ...,
        description="Message history for the orchestrator",
    )
    route_response: str = Field(
        default="",
        description="Router output: 'sql' or 'etl' — determines which sub-agent to invoke",
    )
